cache:
  paths:
    - "target/"

stages:
  - build
  - test
  - lint

stable-build:
  stage: build
  image: rust:latest
  script: cargo build
  artifacts:
    paths:
      - "target/"

stable-test:
  stage: test
  image: rust:latest
  script: cargo test

stable-lint:
  stage: lint
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy
  artifacts:
    paths:
      - "target/"
