stages:
  - lint
  - test
  - fuzz

cache:
  key: stable-${CI_COMMIT_REF_SLUG}
  paths:
    - target/

lint:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --all-features -- -D warnings

stable-test:
  stage: test
  image: rust:latest
  script:
    - cargo test

nightly-test:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test
  allow_failure: true
  cache:
    key: nightly-${CI_COMMIT_REF_SLUG}
    paths:
      - target/

# TODO: find a way to cache the cargo-fuzz installation

fuzz-gif:
  stage: fuzz
  image: rustlang/rust:nightly
  script:
    - cargo install cargo-fuzz
    - ./fuzz.sh gif read_never_panics gif
    - ./fuzz.sh gif write_never_panics gif
    - ./fuzz.sh gif identity gif
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/

fuzz-isobmff:
  stage: fuzz
  image: rustlang/rust:nightly
  script:
    - cargo install cargo-fuzz
    - ./fuzz.sh isobmff read_never_panics mp4
    - ./fuzz.sh isobmff write_never_panics mp4
    - ./fuzz.sh isobmff identity mp4
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/

fuzz-jpeg:
  stage: fuzz
  image: rustlang/rust:nightly
  script:
    - cargo install cargo-fuzz
    - ./fuzz.sh jpeg read_never_panics jpeg
    - ./fuzz.sh jpeg write_never_panics jpeg
    - ./fuzz.sh jpeg identity jpeg
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/

fuzz-png:
  stage: fuzz
  image: rustlang/rust:nightly
  script:
    - cargo install cargo-fuzz
    - ./fuzz.sh png read_never_panics png
    - ./fuzz.sh png write_never_panics png
    - ./fuzz.sh png identity png
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/

fuzz-riff:
  stage: fuzz
  image: rustlang/rust:nightly
  script:
    - cargo install cargo-fuzz
    - ./fuzz.sh riff read_never_panics webp
    - ./fuzz.sh riff write_never_panics webp
    - ./fuzz.sh riff identity webp
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/
