stages:
  - build
  - lint
  - bench

stable:
  stage: build
  image: rust:latest
  script:
    - cargo build -vv
    - cargo test -vv

nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build -vv
    - cargo test -vv
  allow_failure: true

lint:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --all-features -- -D warnings

bench:
  stage: bench
  image: rust:latest
  script:
    - cargo bench 
