stages:
  - build
  - lint
  - test

stable-build:
  stage: build
  image: rust:latest
  script: cargo build

nightly-build:
  stage: build
  image: rustlang/rust:nightly
  script: cargo build
  allow_failure: true

stable-lint:
  stage: build
  image: rust:latest
  script:
    - cargo fmt -- --check
    - cargo clippy

nightly-lint:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo fmt -- --check
    - cargo clippy
  allow_failure: true

stable-test:
  stage: test
  image: rust:latest
  script: cargo test

nightly-test:
  stage: test
  image: rustlang/rust:nightly
  script: cargo test
  allow_failure: true
