stages:
  - lint
  - test
  - fuzz

cache:
  key: stable-${CI_COMMIT_REF_SLUG}
  paths:
    - target/

lint:
  stage: lint
  image: rust:latest
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --all-features -- -D warnings

stable-test:
  stage: test
  image: rust:latest
  script:
    - cargo test

nightly-test:
  stage: test
  image: rustlang/rust:nightly
  script:
    - cargo test
  allow_failure: true
  cache:
    key: nightly-${CI_COMMIT_REF_SLUG}
    paths:
      - target/

# TODO: find a way to cache the cargo-fuzz installation

fuzz-png:
  stage: fuzz
  image: rust:latest
  script:
    - cargo install cargo-fuzz
    - cargo fuzz run --release -s none read_never_panics  -- -max_total_time=150 -seed_inputs=@fuzz/png_seeds
    - cargo fuzz run --release -s none write_never_panics -- -max_total_time=150 -seed_inputs=@fuzz/png_seeds
    - cargo fuzz run --release -s none identity           -- -max_total_time=150 -seed_inputs=@fuzz/png_seeds
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/

fuzz-gif:
  stage: fuzz
  image: rust:latest
  script:
    - cargo install cargo-fuzz
    - cargo fuzz run --release -s none read_never_panics  -- -max_total_time=150 -seed_inputs=@fuzz/gif_seeds
    - cargo fuzz run --release -s none write_never_panics -- -max_total_time=150 -seed_inputs=@fuzz/gif_seeds
    - cargo fuzz run --release -s none identity           -- -max_total_time=150 -seed_inputs=@fuzz/gif_seeds
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/

fuzz-riff:
  stage: fuzz
  image: rust:latest
  script:
    - cargo install cargo-fuzz
    - cargo fuzz run --release -s none read_never_panics  -- -max_total_time=150 -seed_inputs=@fuzz/riff_seeds
    - cargo fuzz run --release -s none write_never_panics -- -max_total_time=150 -seed_inputs=@fuzz/riff_seeds
    - cargo fuzz run --release -s none identity           -- -max_total_time=150 -seed_inputs=@fuzz/riff_seeds
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/

fuzz-jpeg:
  stage: fuzz
  image: rust:latest
  script:
    - cargo install cargo-fuzz
    - cargo fuzz run --release -s none read_never_panics  -- -max_total_time=150 -seed_inputs=@fuzz/jpeg_seeds
    - cargo fuzz run --release -s none write_never_panics -- -max_total_time=150 -seed_inputs=@fuzz/jpeg_seeds
    - cargo fuzz run --release -s none identity           -- -max_total_time=150 -seed_inputs=@fuzz/jpeg_seeds
  artifacts:
    when: on_failure
    paths:
      - fuzz/artifacts/
      - fuzz/corpus/
