stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build -vv
    - cargo test -vv
    - rustup component add clippy
    - cargo clippy -vv --all-targets --all-features -- -D warnings

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build -vv
    - cargo test -vv
  allow_failure: true
