[package]
name = "memedb_core"
version = "0.1.1"
authors = ["SrKomodo", "PeronTheDuck"]
description = "Rust library for reading and writing tags to media files, specifically for the use of categorizing memes."
# homepage = "..."
repository = "https://gitlab.com/memedb/memedb_core"
readme = "README.md"
keywords = ["meme", "db", "tags"]
categories = ["parser-implementations", "encoding", "data-structures"]
license = "GPL-3.0-or-later"
edition = "2018"

[badges]
gitlab = { repository = "memedb/memedb_core" }

[dependencies]
log = { version = "^0.4.8", features = ["max_level_debug", "release_max_level_off"] }
crc = "^1.8.1"
custom_error = "^1.7.1"

[dev-dependencies]
glob = "^0.3.0"
